#### general settings
name: xiaoshu64-512extract-leejh1101-300T
use_tb_logger: true
model: denoising
distortion: deblur
gpu_ids: [1]

sde:
  max_sigma: 50
  T: 300 #1000
  schedule: cosine # linear, cosine
  eps: 0.0005 #0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 2

#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/b110/code/LZL/irsde/codes/datasets/xiaoshuextract/GT/
    dataroot_LQ: /home/b110/code/LZL/irsde/codes/datasets/xiaoshuextract/xiaoshu64-512extract/

    use_shuffle: true
    n_workers: 4 # per GPU
    batch_size: 2
    GT_size: 512
    LR_size: 512
    use_flip: true
    use_rot: true
    color: gray #RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/b110/code/LZL/irsde/codes/datasets/val/xiaoshuextract/GT/
    dataroot_LQ: /home/b110/code/LZL/irsde/codes/datasets/val/xiaoshuextract/64/


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 32 #128  #原64
    depth: 4

# #### path
# path:
#   pretrain_model_G: ~
#   strict_load: true
#   resume_state: ~

## path #resume train
path:
  pretrain_model_G: /home/b110/code/LZL/irsde/experiments/deblurring/xiaoshu64-512extract-leejh1101-300T/models/80000_G.pth
  strict_load: true
  resume_state: /home/b110/code/LZL/irsde/experiments/deblurring/xiaoshu64-512extract-leejh1101-300T/training_state/80000.state




#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [100000, 200000, 300000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e4

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
