#### general settings
name: testRGBleejh-0326
use_tb_logger: true
model: denoising
distortion: derain
gpu_ids: [0]

sde:
  max_sigma: 10
  T: 100 #1000
  schedule: cosine # linear, cosine
  eps: 0.0005 #0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 4

#### datasets
datasets:
  train:
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/b110/code/LZL/irsde/codes/datasets/trainH/128/GT
    dataroot_LQ: /home/b110/code/LZL/irsde/codes/datasets/trainH/128/LQ

    use_shuffle: true
    n_workers: 4 # per GPU
    batch_size: 2
    GT_size: 128
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB #RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/b110/code/LZL/irsde/codes/datasets/testH/128/GT
    dataroot_LQ: /home/b110/code/LZL/irsde/codes/datasets/testH/128/LQ


#### network structures
network_G:
  which_model_G: ConditionalUNet
  setting:
    in_nc: 1
    out_nc: 1
    nf: 128 #128
    depth: 4

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  optimizer: Adam # Adam, AdamW, Lion
  lr_G: !!float 1e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [110000, 230000, 340000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e4

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
