#### general settings
name: xueguan16-512extract-leejh1130-300T-Lion
use_tb_logger: true
model: denoising
distortion: deblur
gpu_ids: [0]

sde:
  max_sigma: 50
  T: 300
  schedule: cosine # linear, cosine
  eps: 0.0005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 2
  
#### datasets
datasets:
  train:
    optimizer: Lion # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /home/b110/code/LZL/irsde/codes/datasets/xueguanextract/xueguan16-512extract/GT/
    dataroot_LQ: /home/b110/code/LZL/irsde/codes/datasets/xueguanextract/xueguan16-512extract/LQ/

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 2
    GT_size: 512
    LR_size: 512
    use_flip: true
    use_rot: true
    color: gray
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /home/b110/code/LZL/irsde/codes/datasets/val/xueguanextract/GT/
    dataroot_LQ: /home/b110/code/LZL/irsde/codes/datasets/val/xueguanextract/16/


#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 64
    enc_blk_nums: [1, 1, 1, 28]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]


#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

# #### path
# path:
#   pretrain_model_G: /home/b110/code/LZL/irsde/experiments/deblurring/xiaoqiu16-512extract-leejh1124-300T-Lion/models/300000_G.pth
#   strict_load: true
#   resume_state: /home/b110/code/LZL/irsde/experiments/deblurring/xiaoqiu16-512extract-leejh1124-300T-Lion/training_state/300000.state

#### training settings: learning rate scheme, loss
train:
  optimizer: Lion # Adam, AdamW, Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [110000, 230000, 340000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 1e4

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
